export const RUIJIN_MISSION = {
  theme: "ruijin",
  introButton: "进入秘密转移现场",
  completionTitle: "队伍已经跨过长征第一渡",
  completionText:
    "你把通信、医疗和机要物资编入队列，在群众守密与夜色掩护下完成转移，并按渡口号令接应各支队伍。中央红军由此离开中央苏区，踏上漫长的战略转移。",
  scenes: [
    {
      id: "ruijin-assembly",
      type: "collect",
      shortTitle: "秘密集结",
      date: "1934年10月10日起",
      title: "从瑞金向于都秘密集结",
      narrative:
        "中央机关和红军部队从瑞金、会昌等地分批向于都转移。队列中不只有作战人员，还要带上维持指挥、通信和救护所必需的器材。",
      fact:
        "10月10日傍晚，两个纵队分别从瑞金、会昌等地向于都开进；各部队在严密保密中陆续完成集结。",
      objective: "把机要、通信和医疗物资编入转移队列",
      completeTitle: "转移队列编组完成",
      completeText: "机要文件、电台和医疗器材已经进入队列，部队可以保持联络并照护伤员。",
      image: "assets/levels/ruijin-departure/cards/03-column.jpg?v=mission-20260710",
      imageAlt: "红军通信、医疗和后勤队伍在赣南山路上集结转移",
      imagePosition: "center",
      sourceId: "source-ruijin-secret-assembly",
      items: [
        { id: "radio", label: "电台与电池", detail: "维持纵队联络", x: 12, y: 61 },
        { id: "medical", label: "担架与药箱", detail: "接应伤员病号", x: 38, y: 69 },
        { id: "documents", label: "机要文件箱", detail: "保存命令与地图", x: 76, y: 50 },
      ],
    },
    {
      id: "ruijin-stealth",
      type: "stealth",
      shortTitle: "守密转移",
      date: "1934年10月中旬",
      title: "把八万余人的行动藏进夜色",
      narrative:
        "大部队必须分批、隐蔽地接近于都。沿途群众协助运输、安置伤员并严守消息，队伍尽量利用夜色行动，避免暴露集结方向。",
      fact:
        "中央红军主力约八万六千人集中在于都一县休整和准备；直到顺利渡河，敌军仍未掌握这一大规模转移。",
      objective: "在侦察光出现时熄灯隐蔽，把队伍带到于都河畔",
      completeTitle: "集结方向没有暴露",
      completeText: "队伍保持了夜间行军秩序，顺利抵达于都河畔的出发区域。",
      successText: "灯火及时熄灭，队伍贴着山影停下",
      mistakeText: "侦察光扫到队尾，整列必须停下重新隐蔽",
      failText: "队伍连续暴露在侦察光下，请重新组织这段秘密转移。",
      advanceStep: 10,
      maxMistakes: 3,
      minHazardGap: 1500,
      maxHazardGap: 2400,
      responseWindow: 1800,
      image: "assets/levels/ruijin-departure/cards/04-farewell.jpg?v=mission-20260710",
      imageAlt: "赣南群众在村口送别分批出发的红军队伍",
      imagePosition: "center",
      sourceId: "source-ruijin-secret-march",
    },
    {
      id: "ruijin-crossing",
      type: "signal",
      shortTitle: "夜渡于都",
      date: "1934年10月17日至20日",
      title: "四天四夜跨过于都河",
      narrative:
        "于都群众帮助架设浮桥、摆渡和运输，中央红军从八个渡口分批渡河。夜色既遮蔽了队伍，也要求各支队列严格服从渡口联络与接应。",
      fact:
        "1934年10月17日至20日，中央红军主力从于都县城东门等八个渡口陆续渡过于都河，开始战略转移。",
      objective: "等待渡口联络号，依次接应各支队伍进入渡河队列",
      completeTitle: "长征第一渡完成",
      completeText: "通信、医疗和后勤队列都已按照渡口号令安全通过，主力踏上西进道路。",
      failText: "渡口联络连续失误，行动有暴露风险，请重新组织接应。",
      signalWindow: 1900,
      maxMistakes: 3,
      groups: ["通信分队", "担架与医疗队", "后勤运输队"],
      image: "assets/levels/ruijin-departure/cards/02-assembly.jpg?v=mission-20260710",
      imageAlt: "红军队伍在夜色中从于都河渡口分批渡河",
      imagePosition: "center",
      sourceId: "source-ruijin-yudu-crossing",
    },
  ],
};
